### ISSUE TITLE
Interactive Messenger

### ISSUE THREAD

**Issue by Arush015** [abr-98/security_cam#1]
Hii !!
I have done some work closely related to it and have an idea that how it can be improved and make it somewhat more useful for the client to catch the third person. I have something for it kindly help me out so that we can together make it an awesome project.

**Comment by abr-98** [comment]
Hi, 
Yeah sure, we can work on the idea.

**Comment by Arush015** [comment]
I have a basic layout regarding the same so I just want to share that first.
